### ISSUE TITLE
Надо было написать vector_set(vector, i, (int)i), а не менять тип.

### ISSUE THREAD

**Issue by Myfasick** [Dovgalyuk/Algorithms#680]
Надо было написать vector_set(vector, i, (int)i), а не менять тип.

_Originally posted by @Dovgalyuk in https://github.com/Dovgalyuk/Algorithms/issues/665#issuecomment-1791888122_
            
<img width="860" alt="image" src="https://user-images.githubusercontent.com/94312727/280261861-f45d0208-56ce-449b-84fc-815e173de1b0.png">
так он все равно ругается на это

**Comment by Dovgalyuk** [comment]
Номеров строк не видно.
