### ISSUE TITLE
Студент просит совет.

### ISSUE THREAD

**Issue by MKBA13** [Dovgalyuk/Algorithms#800]
Здравствуйте Павел Михайлович.
В прошлом году вы вели у меня предмет Структуры данных и алгоритмы. Я хочу с вами встретится и задать несколько вопросом о том, как найти работу юному программисту и как на ней закрепится.
Беседа предполагается на 15-25 минут.
Если вы согласны уделить мне немного времени, то напишите когда и где вам будет удобнее встретится.

С уважением Хаванов Михаил Юрьевич.

**Comment by Dovgalyuk** [comment]
Можно 2 мая в 9:00. Лазаревская 11, кабинет 124.

**Comment by MKBA13** [comment]
Понял. Буду.

**Comment by MKBA13** [comment]
Ещё раз спасибо за беседу. Повторно покручивая вопросы и ответы, я в выцепил для себя важную и полезную мысль.
